IDCI\Bundle\SimpleMetadataBundle\Entity\Metadata:
    exclusion_policy: ALL

    properties:
        id:
            expose: true
            groups: [tms_rest.item]

        namespace:
            expose: true
            groups: [tms_rest.collection, tms_rest.item]

        key:
            expose: true
            groups: [tms_rest.collection, tms_rest.item]

        value:
            expose: true
            groups: [tms_rest.collection, tms_rest.item]

        hash:
            expose: true
            groups: [tms_rest.item]

        objectClassName:
            expose: true
            groups: [tms_rest.item]
            serialized_name: objectClassName

        objectId:
            expose: true
            groups: [tms_rest.item]
            serialized_name: objectId
